# Generated by Django 5.0 on 2023-12-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='username')),
                ('desc', models.TextField(default='SOME STRING')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='pics')),
            ],
        ),
    ]
