# Generated by Django 5.0 on 2023-12-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='newComment',
        ),
    ]
