# Generated by Django 5.0 on 2023-12-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_comment_newcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcomment',
            name='comment',
            field=models.TextField(max_length=200),
        ),
    ]
