# Generated by Django 5.0 on 2023-12-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userdata_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newComment',
        ),
    ]
