# Generated by Django 5.0 on 2023-12-27 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_newcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.userdata')),
            ],
        ),
        migrations.DeleteModel(
            name='newComment',
        ),
    ]
